# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnsi-portal
  namespace: cnsi-system
spec:
  replicas: 1
  selector:
    matchLabels:
      cnsi-portal: portal
  template:
    metadata:
      labels:
        cnsi-portal: portal
    spec:
      serviceAccountName: cnsi-portal-serviceaccount
      containers:
      - name: cloud-native-security-inspector-frontend
        image: projects.registry.vmware.com/cnsi/portal:0.5.0
        imagePullPolicy: Always
        ports:
          - containerPort: 3800       
