apiVersion: goharbor.goharbor.io/v1alpha1
kind: InspectionPolicy
metadata:
  name: inspectionpolicy-sample
spec:
  settingsName: sample-setting
  enabled: true
  workNamespace: demo
  schedule: "*/5 * * * *"
  strategy:
    historyLimit: 4
    suspend: false
    concurrencyRule: "Forbid"
  inspector:
    image: projects.registry.vmware.com/cnsi/inspector:0.3
    kubebenchImage: projects.registry.vmware.com/cnsi/kubebench:0.3
    riskImage: projects.registry.vmware.com/cnsi/risk:0.3
    workloadscannerImage: projects.registry.vmware.com/cnsi/workloadscanner:0.3
    pkgLoadScannerImage: projects.registry.vmware.com/cnsi/pkgloadscanner:0.3.2
    imagePullPolicy: IfNotPresent
    exportConfig:
      openSearch:
        hostport: "https://opensearch-cluster-master.demo:9200"
        username: "admin"
        password: "admin"
        checkCert: false
        mutualTLS: false
      governor:
        clusterId: "65a03970-c53a-4ba1-8d1f-42c9f95d2761"
        url: <please_specify_the_URL_of_governor>
        cspSecretName: "csp-secret"
  inspection:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: default
    baselines:
      - kind: "vulnerability"
        baseline: "Medium"
        version: "v1.1"
        scheme: "application/vnd.security.vulnerability.report; version=1.1"
    actions:
      - kind: "quarantine_vulnerable_workload"
